-- MySQL Script generated by MySQL Workbench
-- Sat Jan 14 17:25:33 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Supplier` (
  `idSupplier` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSupplier`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`State`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`State` (
  `idState` INT NOT NULL,
  `Active` TINYINT NOT NULL,
  PRIMARY KEY (`idState`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Brand` (
  `idBrand` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idBrand`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Size`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Size` (
  `idSize` INT NOT NULL AUTO_INCREMENT,
  `size` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSize`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Color` (
  `idtable1` INT NOT NULL,
  `colorname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtable1`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Price` DOUBLE NOT NULL,
  `Cost` DOUBLE NOT NULL,
  `Qty` INT NOT NULL,
  `Supplier_idSupplier` INT NOT NULL,
  `State_idState1` INT NOT NULL,
  `Brand_idBrand` INT NOT NULL,
  `Size_idSize` INT NOT NULL,
  `Color_idtable1` INT NOT NULL,
  PRIMARY KEY (`idProduct`, `State_idState1`, `Brand_idBrand`, `Size_idSize`, `Color_idtable1`, `Supplier_idSupplier`),
  INDEX `fk_Product_Supplier1_idx` (`Supplier_idSupplier` ASC) VISIBLE,
  INDEX `fk_Product_State2_idx` (`State_idState1` ASC) VISIBLE,
  INDEX `fk_Product_Brand1_idx` (`Brand_idBrand` ASC) VISIBLE,
  INDEX `fk_Product_Size1_idx` (`Size_idSize` ASC) VISIBLE,
  INDEX `fk_Product_Color1_idx` (`Color_idtable1` ASC) VISIBLE,
  CONSTRAINT `fk_Product_Supplier1`
    FOREIGN KEY (`Supplier_idSupplier`)
    REFERENCES `mydb`.`Supplier` (`idSupplier`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_State2`
    FOREIGN KEY (`State_idState1`)
    REFERENCES `mydb`.`State` (`idState`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_Brand1`
    FOREIGN KEY (`Brand_idBrand`)
    REFERENCES `mydb`.`Brand` (`idBrand`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_Size1`
    FOREIGN KEY (`Size_idSize`)
    REFERENCES `mydb`.`Size` (`idSize`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_Color1`
    FOREIGN KEY (`Color_idtable1`)
    REFERENCES `mydb`.`Color` (`idtable1`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `idClient` INT NOT NULL,
  `fname` VARCHAR(45) NULL,
  `lname` VARCHAR(45) NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Paymentmethod`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Paymentmethod` (
  `idPayment method` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Interest rate` FLOAT NOT NULL,
  PRIMARY KEY (`idPayment method`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Taxes type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Taxes type` (
  `idTaxes type` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTaxes type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `idOrder` INT NOT NULL,
  `Product` VARCHAR(45) NULL,
  `price` DOUBLE NULL,
  `totalprice` DOUBLE NULL,
  `Paymentmethod_idPayment method` INT NOT NULL,
  `Taxes type_idTaxes type` INT NOT NULL,
  PRIMARY KEY (`idOrder`, `Paymentmethod_idPayment method`, `Taxes type_idTaxes type`),
  UNIQUE INDEX `price_UNIQUE` (`price` ASC) VISIBLE,
  INDEX `fk_Order_Paymentmethod1_idx` (`Paymentmethod_idPayment method` ASC) VISIBLE,
  INDEX `fk_Order_Taxes type1_idx` (`Taxes type_idTaxes type` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Paymentmethod1`
    FOREIGN KEY (`Paymentmethod_idPayment method`)
    REFERENCES `mydb`.`Paymentmethod` (`idPayment method`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Taxes type1`
    FOREIGN KEY (`Taxes type_idTaxes type`)
    REFERENCES `mydb`.`Taxes type` (`idTaxes type`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order_has_Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order_has_Client` (
  `Order_idOrder` INT NOT NULL,
  `Client_idClient` INT NOT NULL,
  PRIMARY KEY (`Order_idOrder`, `Client_idClient`),
  INDEX `fk_Order_has_Client_Client1_idx` (`Client_idClient` ASC) VISIBLE,
  INDEX `fk_Order_has_Client_Order_idx` (`Order_idOrder` ASC) VISIBLE,
  CONSTRAINT `fk_Order_has_Client_Order`
    FOREIGN KEY (`Order_idOrder`)
    REFERENCES `mydb`.`Order` (`idOrder`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_has_Client_Client1`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `mydb`.`Client` (`idClient`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product_has_Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product_has_Order` (
  `Product_idProduct` INT NOT NULL,
  `Order_idOrder` INT NOT NULL,
  PRIMARY KEY (`Product_idProduct`, `Order_idOrder`),
  INDEX `fk_Product_has_Order_Order1_idx` (`Order_idOrder` ASC) VISIBLE,
  INDEX `fk_Product_has_Order_Product1_idx` (`Product_idProduct` ASC) VISIBLE,
  CONSTRAINT `fk_Product_has_Order_Product1`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `mydb`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_has_Order_Order1`
    FOREIGN KEY (`Order_idOrder`)
    REFERENCES `mydb`.`Order` (`idOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
